#!/bin/bash

cd deploy
echo 'working directory:'
pwd

scp ./docker-compose.yml root@101.43.30.63:/home/apps/IRCT/
scp ./nginx.conf root@101.43.30.63:/home/apps/IRCT/
scp ./restart root@101.43.30.63:/home/apps/IRCT/

# just open when new video/image was added
rm -r ../dist/video # ignore video
rm -r ../dist/img   # ignore image

scp -r ../dist root@101.43.30.63:/home/apps/IRCT/
