#!/bin/bash

cd deploy
echo 'working directory:'
pwd

scp ./docker-compose.yml root@124.221.209.114:/home/apps/IRCT/
scp ./nginx.conf root@124.221.209.114:/home/apps/IRCT/
scp ./restart root@124.221.209.114:/home/apps/IRCT/

# just open when new video/image was added
rm -r ../dist/video # ignore video
rm -r ../dist/img   # ignore image

scp -r ../dist root@124.221.209.114:/home/apps/IRCT/
